### ISSUE TITLE
Any visual materials to imagine this?

### ISSUE THREAD

**Issue by dumblob** [DuncanCragg/OnexOS#1]
Just saw this in my notification panel and skimmed two source files. I find the ideas interesting but am still unable to imagine how this all shall work together.

Do you have any videos or any other concept art to help newcomers understand the overall thing?

Thanks!

**Comment by DuncanCragg** [comment]
Hi! You won't get the vision from the source files just yet, sorry! You could look here: http://object.network to get a better idea of what it's all about. I'll add the link to the repo, thanks for the kick.

The NetMash repo has a much more complete Java version of the ideas, but that would still be quite a job to read that source; also OnexKernel is the newer core of the work, which I'm going to integrate in about a month from now. Thanks for dropping by! :-)

**Comment by dumblob** [comment]
Thanks. I will stay tuned!
